db.coches.insertMany([
{
    Modelo: "Skoda Fabia Comfort 1.4",
    Año: 2005,
    Kms: 80000,
    Fabricante: "Skoda",
    CodFabricante: "SK",
    Precio: 2500 ,
    Combustible: "Diesel",
    Consumo: {Urbano:6.2, Extraurbano:4, Medio:4.8},
    Color: "Gris",
    Plazas: 5,
    LugaresDeVenta: ["Cordoba","Sevilla","Granada"],
    PotenciaMaxima: 64 ,
    SegundaMano: true,
},
{
    Modelo: "Renault Clio Authentique 1.2 16v 75 Euro 6 5p.",
    Año: 2016,
    Kms: 83190,
    Fabricante: "Renault",
    CodFabricante: "RE",
    Precio: 6990 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:7.2, Extraurbano:4.7, Medio:5.6},
    Color: "Rojo",
    Plazas: 5,
    LugaresDeVenta: ["Gran Canaria", "Tenerife"],
    PotenciaMaxima: 75 ,
    SegundaMano: true,
},
{
    Modelo: "Audi A1 Sportback S line 30 TFSI 81kW S tronic 5p.",
    Año: 2019,
    Kms: 19200,
    Fabricante: "Audi",
    CodFabricante: "AU",
    Precio: 23900 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:6, Extraurbano:4.3, Medio:4.9},
    Color: "Blanco",
    Plazas: 5,
    LugaresDeVenta: ["Valencia","Murcia","Sevilla"],
    PotenciaMaxima: 110 ,
    SegundaMano: true,
},
{
    Modelo: "Seat Ibiza 1.4 TDI 66kW 90CV Reference 5p.",
    Año: 2017,
    Kms: 86321,
    Fabricante: "Seat",
    CodFabricante: "SE",
    Precio: 8700 ,
    Combustible: "Diesel",
    Consumo: {Urbano:4.2, Extraurbano:3.4, Medio:3.7},
    Color: "Blanco",
    Plazas: 5,
    LugaresDeVenta: ["Madrid","Valencia"],
    PotenciaMaxima: 90 ,
    SegundaMano: true,
},
{
    Modelo: "Mercedes-Benz Clase E E 300 de 4p.",
    Año: 2020,
    Kms: 0,
    Fabricante: "Mercedes-Benz",
    CodFabricante: "MB",
    Precio: 58299 ,
    Combustible: "Hibrido",
    Consumo: {Urbano:4, Extraurbano:4.2, Medio:4.1},
    Color: "Blanco",
    Plazas: 5,
    LugaresDeVenta: ["Madrid"],
    PotenciaMaxima: 306 ,
    SegundaMano: false,
},
{
    Modelo: "Renault Megane S.T. R.S.Line ETECH",
    Año: 2020,
    Kms: 0,
    Fabricante: "Renault",
    CodFabricante: "RE",
    Precio: 32950 ,
    Combustible: "Hibrido",
    Consumo: {Urbano:3, Extraurbano:3, Medio:3},
    Color: "Azul",
    Plazas: 5,
    LugaresDeVenta: ["Lleida"],
    PotenciaMaxima: 160 ,
    SegundaMano: false,
},
{
    Modelo: "Alfa Romeo Stelvio 2.0",
    Año: 2020,
    Kms: 0,
    Fabricante: "Alfa Romeo",
    CodFabricante: "AR",
    Precio: 55281 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:8.9, Extraurbano:5.9, Medio:7},
    Color: "Rojo",
    Plazas: 5,
    LugaresDeVenta: ["Tarragona","Malaga","Barcelona"],
    PotenciaMaxima: 200 ,
    SegundaMano: false,
},
{
    Modelo: "BMW Serie 2 218dA Gran Coupe 4p.",
    Año: 2021,
    Kms: 0,
    Fabricante: "BMW",
    CodFabricante: "BMW",
    Precio: 41900 ,
    Combustible: "Diesel",
    Consumo: {Urbano:6.2, Extraurbano:3.8, Medio:4.2},
    Color: "Negro",
    Plazas: 5,
    LugaresDeVenta: ["Madrid","Valencia","Cordoba"],
    PotenciaMaxima: 150 ,
    SegundaMano: false,
},
{
    Modelo: "Volkswagen Golf Business 1.0 TSI 85kW 115CV 5p",
    Año: 2019,
    Kms: 35402,
    Fabricante: "Volkswagen",
    CodFabricante: "VW",
    Precio: 15800 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:6.6, Extraurbano:4.6, Medio:4.8},
    Color: "Blanco",
    Plazas: 5,
    LugaresDeVenta: ["Madrid","Sevilla"],
    PotenciaMaxima: 115 ,
    SegundaMano: true,
},
{
    Modelo: "Opel Corsa 1.3 CDTi Expression 55kW 75CV 5p",
    Año: 2017,
    Kms: 97218,
    Fabricante: "Opel",
    CodFabricante: "OP",
    Precio: 6990 ,
    Combustible: "Diesel",
    Consumo: {Urbano:4.6, Extraurbano:3.3, Medio:3.8},
    Color: "Verde",
    Plazas: 5,
    LugaresDeVenta: ["Cordoba","Almeria"],
    PotenciaMaxima: 75 ,
    SegundaMano: true,
},
{
    Modelo: "Toyota Yaris 1.0 70 Active 3p",
    Año: 2017,
    Kms: 83750,
    Fabricante: "Toyota",
    CodFabricante: "TY",
    Precio: 9900 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:5.2, Extraurbano:3.8, Medio:4.3},
    Color: "Negro",
    Plazas: 5,
    LugaresDeVenta: ["Badajoz","Jaen"],
    PotenciaMaxima: 69 ,
    SegundaMano: true,
},
{
    Modelo: "Opel Mokka X 1.6 CDTi 100kW 4X2 SS Excellence 5p",
    Año: 2018,
    Kms: 79000,
    Fabricante: "Opel",
    CodFabricante: "OP",
    Precio: 15500 ,
    Combustible: "Diesel",
    Consumo: {Urbano:6.5, Extraurbano:4.9, Medio:5.7},
    Color: "Azul",
    Plazas: 5,
    LugaresDeVenta: ["Badajoz","Sevilla"],
    PotenciaMaxima: 136 ,
    SegundaMano: true,
},
{
    Modelo: "Ford Grand CMax 1.5 TDCi 88kW 120CV Trend 5p",
    Año: 2017,
    Kms: 83838,
    Fabricante: "Ford",
    CodFabricante: "FO",
    Precio: 15950 ,
    Combustible: "Diesel",
    Consumo: {Urbano:4.9, Extraurbano:4.1, Medio:4.4},
    Color: "Blanco",
    Plazas: 5,
    LugaresDeVenta: ["Granada","Malaga","Madrid","Valencia"],
    PotenciaMaxima: 120,
    SegundaMano: true,
},
{
    Modelo: "Mercedes-Benz Clase C C 200 CDI BE Blue Efficiency Edition 4p.",
    Año: 2012,
    Kms: 99000,
    Fabricante: "Mercedes-Benz",
    CodFabricante: "MB",
    Precio: 14900 ,
    Combustible: "Diesel",
    Consumo: {Urbano:6, Extraurbano:4.2, Medio:4.9},
    Color: "Gris",
    Plazas: 5,
    LugaresDeVenta: ["Badajoz"],
    PotenciaMaxima: 136 ,
    SegundaMano: true,
},
{
    Modelo: "Kia Ceed Tourer Tourer 1.0 TGDi 88kW 120CV Tech 5p",
    Año: 2021,
    Kms: 0,
    Fabricante: "KIA",
    CodFabricante: "KIA",
    Precio: 19800 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:6.5, Extraurbano:5, Medio:5.7},
    Color: "Azul",
    Plazas: 5,
    LugaresDeVenta: ["Vizcaya","Bilbao"],
    PotenciaMaxima: 120 ,
    SegundaMano: false,
},
{
    Modelo: "BMW X3 XDRIVE20D 5p",
    Año: 2021,
    Kms: 145000,
    Fabricante: "BMW",
    CodFabricante: "BMW",
    Precio: 53500 ,
    Combustible: "Diesel",
    Consumo: {Urbano:5.3, Extraurbano:4.9, Medio:5.1},
    Color: "Gris",
    Plazas: 5,
    LugaresDeVenta: ["Sevilla","Granada"],
    PotenciaMaxima: 64 ,
    SegundaMano: true,
},
{
    Modelo: "Volkswagen Golf 1.6 CONCEPTLINE 3p",
    Año: 2001,
    Kms: 195000,
    Fabricante: "Volkswagen",
    CodFabricante: "VW",
    Precio: 1850 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:6, Extraurbano:5.5, Medio:5.7},
    Color: "Rojo",
    Plazas: 5,
    LugaresDeVenta: ["Barcelona","Bilbao"],
    PotenciaMaxima: 105 ,
    SegundaMano: true,
},
{
    Modelo: "Seat Leon 1.6 SPORTS LIMITED 5p",
    Año: 2002,
    Kms: 167000,
    Fabricante: "Seat",
    CodFabricante: "SE",
    Precio: 2400 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:9.4, Extraurbano:5.6, Medio:7},
    Color: "Negro",
    Plazas: 5,
    LugaresDeVenta: ["Barcelona","Valencia","Madrid"],
    PotenciaMaxima: 105 ,
    SegundaMano: true,
},
{
    Modelo: "Volkswagen TRoc Advance 1.0 TSI 85kW 115CV 5p",
    Año: 2019,
    Kms: 23124,
    Fabricante: "Volkswagen",
    CodFabricante: "VW",
    Precio: 18995 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:6.2, Extraurbano:4.6, Medio:5.2},
    Color: "Rojo",
    Plazas: 5,
    LugaresDeVenta: ["Las Palmas","Tenerife"],
    PotenciaMaxima: 115 ,
    SegundaMano: true,
},
{
    Modelo: "Citroen C3 Aircross PureTech 96kW 130CV SS EAT6 SHINE 5p",
    Año: 2020,
    Kms: 0,
    Fabricante: "Citroen",
    CodFabricante: "CI",
    Precio: 19900 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:5.9, Extraurbano:4.5, Medio:5},
    Color: "Blanco",
    Plazas: 5,
    LugaresDeVenta: ["Cordoba","Barcelona","Cadiz"],
    PotenciaMaxima: 131 ,
    SegundaMano: false,
},
{
    Modelo: "Ford KA 1.3 3p",
    Año: 2004,
    Kms: 134222,
    Fabricante: "Ford",
    CodFabricante: "FO",
    Precio: 1950 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:8.4, Extraurbano:4.9, Medio:6.2},
    Color: "Rojo",
    Plazas: 4,
    LugaresDeVenta: ["Madrid","Sevilla","Malaga","Badajoz"],
    PotenciaMaxima: 70 ,
    SegundaMano: true,
},
{
    Modelo: "Citroen C2 1.4 HDI VTR 3p",
    Año: 2005,
    Kms: 240000,
    Fabricante: "Citroen",
    CodFabricante: "CI",
    Precio: 1400 ,
    Combustible: "Diesel",
    Consumo: {Urbano:5.1, Extraurbano:3.6, Medio:4.1},
    Color: "Negro",
    Plazas: 4,
    LugaresDeVenta: ["Madrid","Cadiz"],
    PotenciaMaxima: 70 ,
    SegundaMano: true,
},
{
    Modelo: "Peugeot 206 XT 110 5p",
    Año: 2003,
    Kms: 196.000,
    Fabricante: "Peugeot",
    CodFabricante: "PE",
    Precio: 1499 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:8.6, Extraurbano:5.1, Medio:6.4},
    Color: "Gris",
    Plazas: 5,
    LugaresDeVenta: ["Madrid","Barcelona"],
    PotenciaMaxima: 110 ,
    SegundaMano: true,
},
{
    Modelo: "Renault Scenic CONFORT DYNAMIQUE 1.9DCI 5p",
    Año: 2003,
    Kms: 240000,
    Fabricante: "Renault",
    CodFabricante: "RE",
    Precio: 1400 ,
    Combustible: "Diesel",
    Consumo: {Urbano:6.3, Extraurbano:4.5, Medio:5.1},
    Color: "Gris",
    Plazas: 5,
    LugaresDeVenta: ["Sevilla","Cadiz"],
    PotenciaMaxima: 100 ,
    SegundaMano: true,
},
{
    Modelo: "Audi 100 100 2.3 4p",
    Año: 1992,
    Kms: 105000,
    Fabricante: "Audi",
    CodFabricante: "AU",
    Precio: 2000 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:8, Extraurbano:6, Medio:7},
    Color: "Verde",
    Plazas: 5,
    LugaresDeVenta: ["Asturias"],
    PotenciaMaxima: 133 ,
    SegundaMano: true,
},
{
    Modelo: "Volkswagen Polo 1.4 Auto Trendline 75CV 3p",
    Año: 2002,
    Kms: 138700,
    Fabricante: "Volkswagen",
    CodFabricante: "VW",
    Precio: 1200 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:5.2, Extraurbano:4, Medio:4.8},
    Color: "Azul",
    Plazas: 5,
    LugaresDeVenta: ["Madrid","Asturias"],
    PotenciaMaxima: 75 ,
    SegundaMano: true,
},
{
    Modelo: "KIA Sportage 1.6 MHEV Concept 85kW 115CV 4x2 5p",
    Año: 2020,
    Kms: 0,
    Fabricante: "KIA",
    CodFabricante: "KIA",
    Precio: 23400 ,
    Combustible: "Hibrido",
    Consumo: {Urbano:4.2, Extraurbano:4.1, Medio:4.2},
    Color: "Blanco",
    Plazas: 5,
    LugaresDeVenta: ["Alicante","Valencia"],
    PotenciaMaxima: 115 ,
    SegundaMano: false,
},
{
    Modelo: "Ford Fiesta 1.25 Duratec 82cv Trend 5p",
    Año: 2014,
    Kms: 127000,
    Fabricante: "Ford",
    CodFabricante: "FO",
    Precio: 6000 ,
    Combustible: "Gasolina",
    Consumo: {Urbano:6.8, Extraurbano:4.2, Medio:5.2},
    Color: "Verde",
    Plazas: 5,
    LugaresDeVenta: ["Alicante","Valencia","Madrid"],
    PotenciaMaxima: 82 ,
    SegundaMano: true,
},
{
    Modelo: "Ford Focus 1.6 TDCi 115cv Titanium Sportbreak 5p",
    Año: 2011,
    Kms: 99.990,
    Fabricante: "Ford",
    CodFabricante: "FO",
    Precio: 8790 ,
    Combustible: "Diesel",
    Consumo: {Urbano:5.1, Extraurbano:3.7, Medio:4.2},
    Color: "Rojo",
    Plazas: 5,
    LugaresDeVenta: ["Barcelona","Sevilla"],
    PotenciaMaxima: 115 ,
    SegundaMano: true,
},
{
    Modelo: "Skoda Octavia 1.6 TDI CR 105cv Ambition 5p",
    Año: 2013,
    Kms: 114484,
    Fabricante: "Skoda",
    CodFabricante: "SK",
    Precio: 9500 ,
    Combustible: "Diesel",
    Consumo: {Urbano:4.6, Extraurbano:3.3, Medio:3.8},
    Color: "Gris",
    Plazas: 5,
    LugaresDeVenta: ["Valladolid","Bilbao","Galicia"],
    PotenciaMaxima: 105 ,
    SegundaMano: true,
},
])